export const SMALL_DATA = 'SMALL DATA'
export const BIG_DATA = 'BIG DATA'
export const ADD_DATA = 'ADD DATA'
export const SET_SMALL_VOLUME = 'SMALL VOLUME'
export const SET_SMALL_LOADING = 'SET SMALL LOADING'
export const SET_BIG_LOADING = 'SET BIG LOADING'
export const SET_INFO = 'SET INFO'
export const SET_ERROR = 'SET ERROR'
